project_id = "jmsngfbiyqzzwhdgouoo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.ai-inference]
verify_jwt = false

[functions.multi-timeframe-analysis]
verify_jwt = false

[functions.volume-profile-analysis]
verify_jwt = false

[functions.pattern-recognition]
verify_jwt = false

[functions.order-flow-analysis]
verify_jwt = false

[functions.risk-management]
verify_jwt = false

[functions.signal-aggregation]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15